
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
server:
  port: 5251
spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/StoresMgt
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
